import { container } from 'tsyringe';
import { PrismaClient } from '@prisma/client';
import { prisma } from '@config/database';
import { AuthRepository } from '@modules/auth/auth.repository';
import { AuthService } from '@modules/auth/auth.service';
import { UsersRepository } from '@modules/users/users.repository';
import { UsersService } from '@modules/users/users.service';
import { CompaniesRepository } from '@modules/companies/companies.repository';
import { CompaniesService } from '@modules/companies/companies.service';
import { ActionPlansRepository } from '@modules/action-plans/action-plans.repository';
import { ActionPlansService } from '@modules/action-plans/action-plans.service';
import { AnalyticsRepository } from '@modules/analytics/analytics.repository';
import { AnalyticsService } from '@modules/analytics/analytics.service';
import { BillingRepository } from '@modules/billing/billing.repository';
import { BillingService } from '@modules/billing/billing.service';
import { ColumnsRepository } from '@modules/columns/columns.repository';
import { ColumnsService } from '@modules/columns/columns.service';
import { RisksRepository } from '@modules/risks/risks.repository';
import { RisksService } from '@modules/risks/risks.service';
import { SheetsService } from '@modules/action-plan-sheets/sheets.service';
import { CalendarRepository } from '@modules/calendar/calendar.repository';
import { CalendarService } from '@modules/calendar/calendar.service';
import { AuditService } from '@shared/audit/audit.service';
import { TenantPolicyService } from '@shared/policies/tenant-policy.service';
import { TenantQuotaService } from '@shared/limits/tenant-quota.service';
import { MailService } from '@shared/mail/mail.service';
import { createBillingProvider } from '@modules/billing/providers';

export function registerDependencies(): void {
  container.registerInstance('PrismaClient', prisma as unknown as PrismaClient);
  container.registerSingleton(AuditService);
  container.registerSingleton(TenantPolicyService);
  container.registerSingleton(MailService);
  container.registerSingleton(TenantQuotaService);
  container.registerSingleton(AuthRepository);
  container.registerSingleton(AuthService);
  container.registerSingleton(UsersRepository);
  container.registerSingleton(UsersService);
  container.registerSingleton(CompaniesRepository);
  container.registerSingleton(CompaniesService);
  container.registerSingleton(ActionPlansRepository);
  container.registerSingleton(ActionPlansService);
  container.registerSingleton(AnalyticsRepository);
  container.registerSingleton(AnalyticsService);
  container.registerSingleton(BillingRepository);
  container.registerSingleton(BillingService);
  container.registerSingleton(ColumnsRepository);
  container.registerSingleton(ColumnsService);
  container.registerSingleton(RisksRepository);
  container.registerSingleton(RisksService);
  container.registerSingleton(SheetsService);
  container.registerSingleton(CalendarRepository);
  container.registerSingleton(CalendarService);
  container.registerInstance('BillingProvider', createBillingProvider());
}
